name: Python Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  # Optional: allow read access to pull request metadata if needed
  # pull-requests: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Match your project's Python version
    # Install dependencies if needed for Ruff plugins or type checking
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt # Or use pdm install
    - name: Install Ruff
      run: pip install ruff
    - name: Run Ruff Formatter Check
      run: ruff format --check .
    - name: Run Ruff Linter
      run: ruff check . 